/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tinz.algs.brownianmotion;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.awt.image.ImageObserver;

/**
 *
 * @author tinz
 */
public class DrawPane extends javax.swing.JPanel implements ImageObserver {

    /**
     * Creates new form DrawPane
     */
    private BrownianMotion bm;

    public DrawPane(BrownianMotion bm) {
        initComponents();
        this.bm = bm;
    }

    boolean fillBackground = false;

    @Override
    protected void paintComponent(Graphics g) {
        if (!fillBackground) {
            g.setColor(Color.black);
            g.fillRect(0, 0, g.getClipBounds().width, g.getClipBounds().height);
        }

        g.setColor(new Color(1, 0, 0));
        int r = 0, gr = 0, b = 0;
        for (int i = bm.getPoints().size() < 1000 ? 0 : bm.getPoints().size() - 1000; i < bm.getPoints().size() - 1; i++) {
            g.drawLine(bm.getPoints().get(i).x,
                    bm.getPoints().get(i).y,
                    bm.getPoints().get(i + 1).x,
                    bm.getPoints().get(i + 1).y);
            g.setColor(new Color(r, gr, b));
            if (r == 255) {
                r = 0;
                gr++;
            } else {
                r++;
            }
            if (gr == 255) {
                gr = 0;
                b++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
